version: '3.1'

services:
  crawler:
    build:
      context: .
      dockerfile: Dockerfile

    links:
      - mongo
      - redis

  mongo:
    image: mongo:4.2.8-bionic
    restart: always
    ports:
      - 27017:27017

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
